'use client';

import { useState } from 'react';
import { AlertTriangle, CheckCircle2, Clock3, GitBranch, PackageCheck, Plus, UserRoundCheck } from 'lucide-react';
import { DetailDrawer } from '@/components/ui/DetailDrawer';
import { Toast } from '@/components/ui/Toast';
import { approvalWorkflows, custodianCoverage } from '@/lib/mock/admin.mock';
import { ActionMenu, AdminPageHeader, Field, inputClass, MetricCard, Panel, PrimaryButton, SearchToolbar, SecondaryButton, StatusChip, TableWrap, tdClass, thClass } from './AdminUi';

export function AdminGovernancePages({ slug }: Readonly<{ slug: 'approval-configuration' | 'custodian-assignments' }>) {
  return slug === 'approval-configuration' ? <ApprovalWorkflowsPage /> : <CustodianCoveragePage />;
}

function ApprovalWorkflowsPage() {
  const [workflows, setWorkflows] = useState(approvalWorkflows);
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState('All');
  const [selected, setSelected] = useState<(typeof approvalWorkflows)[number] | null>(null);
  const [creating, setCreating] = useState(false);
  const [toast, setToast] = useState('');
  const rows = workflows.filter((workflow) => (filter === 'All' || workflow.status === filter || workflow.requestType === filter) && Object.values(workflow).join(' ').toLowerCase().includes(search.toLowerCase()));
  return <div className="space-y-4"><AdminPageHeader title="Approval Workflows" detail="Design versioned approval routes using request scope, approver responsibility, SLA targets, alternates, and escalation rules." action={<PrimaryButton icon={Plus} onClick={() => setCreating(true)}>New workflow</PrimaryButton>} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Published workflows" value="3" detail="Covering all request types" tone="green" icon={CheckCircle2} /><MetricCard label="Drafts" value="1" detail="Urgent request workflow" tone="amber" icon={GitBranch} /><MetricCard label="SLA target" value="24h" detail="Standard approval route" tone="blue" icon={Clock3} /><MetricCard label="Coverage gaps" value="1" detail="Alternate approver missing" tone="red" icon={AlertTriangle} /></div>
    <div className="border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-900"><strong>Version control:</strong> Published workflows remain immutable. Editing creates a new draft so historical approvals retain their original route.</div>
    <SearchToolbar value={search} onChange={setSearch} filterLabel="All workflows" filterValue={filter} filterOptions={['All', 'Published', 'Draft', 'New asset', 'Replacement', 'Supply']} onFilterChange={setFilter} />
    <Panel title="Workflow Catalogue" detail="Published and draft routing definitions"><TableWrap><table className="min-w-[1180px] w-full"><thead><tr><th className={thClass}>Workflow</th><th className={thClass}>Request type</th><th className={thClass}>Scope</th><th className={thClass}>Trigger</th><th className={thClass}>Stages</th><th className={thClass}>SLA</th><th className={thClass}>Version</th><th className={thClass}>Status</th><th className={`${thClass} text-right`}>Actions</th></tr></thead><tbody>{rows.map((workflow) => <tr key={workflow.id} className="hover:bg-slate-50"><td className={tdClass}><button type="button" onClick={() => setSelected(workflow)} className="text-left font-bold text-slate-950">{workflow.name}<span className="block text-xs font-normal text-slate-500">{workflow.id}</span></button></td><td className={tdClass}>{workflow.requestType}</td><td className={tdClass}>{workflow.scope}</td><td className={tdClass}>{workflow.trigger}</td><td className={tdClass}>{workflow.stages}</td><td className={tdClass}>{workflow.sla}</td><td className={tdClass}>{workflow.version}</td><td className={tdClass}><StatusChip status={workflow.status} /></td><td className={`${tdClass} text-right`}><ActionMenu actions={[{ label: 'View route', onClick: () => setSelected(workflow) }, { label: 'Test workflow', onClick: () => setToast(`Simulation passed for ${workflow.name}.`) }, { label: 'Create new version', onClick: () => { const copy = { ...workflow, id: `${workflow.id}-D${workflows.length}`, version: `v${Number(workflow.version.slice(1)) + 1}`, status: 'Draft' }; setWorkflows((current) => [...current, copy]); setToast(`Draft ${copy.version} created from ${workflow.version} in frontend mock state.`); } }]} /></td></tr>)}</tbody></table></TableWrap></Panel>
    <DetailDrawer open={Boolean(selected)} title={selected?.name ?? 'Workflow'} onClose={() => setSelected(null)}>{selected && <div className="space-y-5"><div className="flex items-center gap-3"><div className="flex-1 border border-slate-200 p-3 text-center"><p className="text-xs text-slate-500">Stage 1</p><p className="mt-1 text-sm font-bold">Approving Officer</p><p className="text-xs text-slate-500">Primary + alternate</p></div><span className="text-slate-400">-&gt;</span><div className="flex-1 border border-slate-200 p-3 text-center"><p className="text-xs text-slate-500">Stage 2</p><p className="mt-1 text-sm font-bold">Custodian</p><p className="text-xs text-slate-500">Availability check</p></div></div>{selected.stages > 2 && <div className="border border-slate-200 p-3 text-center"><p className="text-xs text-slate-500">Stage 3</p><p className="mt-1 text-sm font-bold">Property Officer validation</p></div>}{[['Scope', selected.scope], ['Trigger', selected.trigger], ['SLA', selected.sla], ['Published version', selected.version]].map(([label, value]) => <div key={label} className="flex justify-between border-b border-slate-100 pb-3 text-sm"><span className="text-slate-500">{label}</span><span className="font-semibold">{value}</span></div>)}<div className="flex gap-2"><PrimaryButton onClick={() => setToast('Workflow simulation passed.')}>Test workflow</PrimaryButton><SecondaryButton onClick={() => setToast('A new draft version was created in frontend mock state.')}>Create draft</SecondaryButton></div></div>}</DetailDrawer>
    <DetailDrawer open={creating} title="Create approval workflow" onClose={() => setCreating(false)}><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const workflow = { id: `WF-${String(workflows.length + 1).padStart(3, '0')}`, name: String(data.get('name')), requestType: String(data.get('requestType')), scope: String(data.get('scope')), trigger: String(data.get('trigger')), stages: Number(data.get('stages')), sla: String(data.get('sla')), version: 'v1', status: 'Draft' }; setWorkflows((current) => [...current, workflow]); setCreating(false); setToast(`${workflow.name} draft was created in frontend mock state.`); }}><Field label="Workflow name"><input name="name" required className={inputClass} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Request type"><select name="requestType" className={inputClass}><option>New asset</option><option>Replacement</option><option>Supply</option></select></Field><Field label="SLA"><select name="sla" className={inputClass}><option>24 hours</option><option>48 hours</option><option>8 hours</option></select></Field></div><Field label="Organizational scope"><select name="scope" className={inputClass}><option>All offices</option><option>Selected organizational unit</option><option>Operations only</option></select></Field><Field label="Routing trigger"><input name="trigger" required className={inputClass} placeholder="Any value, high priority, or useful-life condition" /></Field><Field label="Approval stages"><input name="stages" type="number" min="1" max="5" defaultValue="2" className={inputClass} /></Field><Field label="Stage 1 approver"><select className={inputClass}><option>Approving Officer for requester unit</option><option>Named alternate approver</option></select></Field><Field label="Escalation rule"><select className={inputClass}><option>Notify primary and alternate at 80% of SLA</option><option>Escalate after SLA breach</option></select></Field><PrimaryButton type="submit">Save draft</PrimaryButton></form></DetailDrawer><Toast message={toast} /></div>;
}

function CustodianCoveragePage() {
  const [assignments, setAssignments] = useState(custodianCoverage);
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState('All');
  const [selected, setSelected] = useState<(typeof custodianCoverage)[number] | null>(null);
  const [creating, setCreating] = useState(false);
  const [toast, setToast] = useState('');
  const rows = assignments.filter((coverage) => (filter === 'All' || coverage.assignment === filter || coverage.coverage === filter || coverage.assetFamily === filter) && Object.values(coverage).join(' ').toLowerCase().includes(search.toLowerCase()));
  return <div className="space-y-4"><AdminPageHeader title="Custodian Coverage" detail="Assign accountable primary and alternate custodians by office, physical location, and asset family with effective dates." action={<PrimaryButton icon={Plus} onClick={() => setCreating(true)}>Assign custodian</PrimaryButton>} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Primary custodians" value="3" detail="ICT, property, and supplies" tone="blue" icon={PackageCheck} /><MetricCard label="Alternates" value="1" detail="Two areas have no alternate" tone="amber" icon={UserRoundCheck} /><MetricCard label="Coverage gaps" value="1" detail="Regional Coordination Desk" tone="red" icon={AlertTriangle} /><MetricCard label="Expiring soon" value="1" detail="Within the next 90 days" tone="amber" icon={Clock3} /></div>
    <SearchToolbar value={search} onChange={setSearch} filterLabel="All coverage" filterValue={filter} filterOptions={['All', 'Primary', 'Alternate', 'Covered', 'Gap', 'ICT equipment', 'PPE and SEP', 'Supplies']} onFilterChange={setFilter} />
    <Panel title="Coverage Assignments" detail="A single accountable primary custodian is required for each scope"><TableWrap><table className="w-full"><thead><tr><th className={thClass}>Custodian</th><th className={thClass}>Assignment</th><th className={thClass}>Office</th><th className={thClass}>Location</th><th className={thClass}>Asset family</th><th className={thClass}>Effective dates</th><th className={thClass}>Coverage</th><th className={`${thClass} text-right`}>Actions</th></tr></thead><tbody>{rows.map((coverage) => <tr key={coverage.id} className="hover:bg-slate-50"><td className={tdClass}><button type="button" onClick={() => setSelected(coverage)} className={`text-left font-bold ${coverage.custodian === 'Unassigned' ? 'text-red-700' : 'text-slate-950'}`}>{coverage.custodian}<span className="block text-xs font-normal text-slate-500">{coverage.id}</span></button></td><td className={tdClass}>{coverage.assignment}</td><td className={tdClass}>{coverage.office}</td><td className={tdClass}>{coverage.location}</td><td className={tdClass}>{coverage.assetFamily}</td><td className={tdClass}>{coverage.start}<span className="block text-xs text-slate-500">to {coverage.end}</span></td><td className={tdClass}><StatusChip status={coverage.coverage} /></td><td className={`${tdClass} text-right`}><ActionMenu actions={[{ label: 'View coverage', onClick: () => setSelected(coverage) }, { label: 'Edit assignment', onClick: () => setToast(`Edit opened for ${coverage.id}.`) }, { label: 'Assign alternate', onClick: () => setToast(`Alternate assignment opened for ${coverage.office}.`) }, { label: 'End assignment', danger: true, onClick: () => setToast('End-date confirmation opened.') }]} /></td></tr>)}</tbody></table></TableWrap></Panel>
    <Panel title="Coverage Validation" detail="Issues that could leave property without accountable custody"><div className="grid gap-0 md:grid-cols-3">{[['Unassigned scope', 'Regional Coordination Desk - ICT equipment', 'Resolve gap'], ['Missing alternate', 'Property Unit - PPE and SEP', 'Assign alternate'], ['Upcoming expiry', 'Ramon Lim - Dec 31, 2026', 'Review assignment']].map(([title, detail, action], index) => <div key={title} className={`p-4 ${index > 0 ? 'border-t border-slate-100 md:border-l md:border-t-0' : ''}`}><p className="text-sm font-bold text-slate-950">{title}</p><p className="mt-1 text-xs text-slate-500">{detail}</p><button type="button" onClick={() => setToast(`${action} opened.`)} className="mt-3 text-xs font-bold text-blue-700">{action}</button></div>)}</div></Panel>
    <DetailDrawer open={Boolean(selected)} title={selected?.custodian ?? 'Coverage details'} onClose={() => setSelected(null)}>{selected && <div className="space-y-4">{Object.entries(selected).filter(([key]) => key !== 'id').map(([key, value]) => <div key={key} className="flex justify-between gap-4 border-b border-slate-100 pb-3 text-sm"><span className="capitalize text-slate-500">{key.replace(/([A-Z])/g, ' $1')}</span><span className="text-right font-semibold">{value}</span></div>)}<div className="border border-blue-200 bg-blue-50 p-3 text-xs text-blue-900">Changing custody coverage records the previous assignment and effective end date for audit reference.</div></div>}</DetailDrawer>
    <DetailDrawer open={creating} title="Assign custodian" onClose={() => setCreating(false)}><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const assignment = { id: `COV-${String(assignments.length + 1).padStart(3, '0')}`, custodian: String(data.get('custodian')), assignment: String(data.get('assignment')), office: String(data.get('office')), location: String(data.get('location')), assetFamily: String(data.get('assetFamily')), start: String(data.get('start')), end: String(data.get('end')) || '-', coverage: 'Covered' }; setAssignments((current) => [...current, assignment]); setCreating(false); setToast(`${assignment.custodian} was assigned to ${assignment.office} in frontend mock state.`); }}><Field label="Custodian"><select name="custodian" className={inputClass}><option>Paolo Cruz</option><option>Leah Garcia</option><option>Ramon Lim</option></select></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Assignment"><select name="assignment" className={inputClass}><option>Primary</option><option>Alternate</option></select></Field><Field label="Asset family"><select name="assetFamily" className={inputClass}><option>ICT equipment</option><option>PPE and SEP</option><option>Supplies</option></select></Field></div><Field label="Office"><input name="office" required className={inputClass} /></Field><Field label="Physical location"><input name="location" required className={inputClass} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Start date"><input name="start" required type="date" className={inputClass} /></Field><Field label="End date (optional)"><input name="end" type="date" className={inputClass} /></Field></div><PrimaryButton type="submit">Save assignment</PrimaryButton></form></DetailDrawer><Toast message={toast} /></div>;
}
