'use client';

import { useMemo, useState } from 'react';
import { KeyRound, Plus, ShieldCheck, UserCheck, Users } from 'lucide-react';
import { DetailDrawer } from '@/components/ui/DetailDrawer';
import { Toast } from '@/components/ui/Toast';
import { accessReviews, adminRoles, adminUsers, organizationUnits, permissionGroups } from '@/lib/mock/admin.mock';
import type { AdminRole, AdminUser } from '@/lib/mock/admin.mock';
import { ActionMenu, AdminPageHeader, Field, inputClass, MetricCard, Panel, PrimaryButton, SearchToolbar, SecondaryButton, StatusChip, TableWrap, tdClass, thClass } from './AdminUi';

type IdentitySlug = 'users' | 'roles' | 'access-reviews' | 'organizational-units';

export function AdminIdentityPages({ slug }: Readonly<{ slug: IdentitySlug }>) {
  if (slug === 'users') return <UsersPage />;
  if (slug === 'roles') return <RolesPage />;
  if (slug === 'access-reviews') return <AccessReviewsPage />;
  return <OrganizationPage />;
}

function UsersPage() {
  const [users, setUsers] = useState<AdminUser[]>(adminUsers);
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState('All');
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [creating, setCreating] = useState(false);
  const [toast, setToast] = useState('');
  const rows = useMemo(() => users
    .filter((user) => filter === 'All' || user.status === filter || user.accountType === filter || user.mfa === filter)
    .filter((user) => Object.values(user).flat().join(' ').toLowerCase().includes(search.toLowerCase())), [filter, search, users]);
  const selected = users.find((user) => user.id === selectedId);
  const updateUser = (id: string, changes: Partial<AdminUser>, message: string) => {
    setUsers((current) => current.map((user) => user.id === id ? { ...user, ...changes } : user));
    setToast(message);
  };

  return <div className="space-y-4">
    <AdminPageHeader title="Users & Accounts" detail="Manage the minimum identity data required for system access, account lifecycle, MFA enrollment, and role governance." action={<PrimaryButton icon={Plus} onClick={() => setCreating(true)}>Create account</PrimaryButton>} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="Active accounts" value="125" detail="Three lifecycle actions pending" tone="blue" icon={Users} /><MetricCard label="Privileged" value="24" detail="Quarterly review required" tone="amber" icon={KeyRound} /><MetricCard label="Locked" value="1" detail="Manual review needed" tone="red" icon={ShieldCheck} /><MetricCard label="Dormant" value="8" detail="Inactive for 45+ days" tone="amber" icon={UserCheck} /><MetricCard label="MFA coverage" value="94%" detail="7 users not enrolled" tone="green" icon={ShieldCheck} /></div>
    <SearchToolbar value={search} onChange={setSearch} filterLabel="All accounts" filterValue={filter} filterOptions={['All', 'Active', 'Locked', 'Dormant', 'Privileged', 'Not enrolled']} onFilterChange={setFilter} />
    <Panel title="Account Directory" detail={`${rows.length} accounts shown - deactivation preserves audit history`}>
      <TableWrap><table className="min-w-[1180px] w-full"><thead><tr><th className={thClass}>User</th><th className={thClass}>Office</th><th className={thClass}>Roles</th><th className={thClass}>Account type</th><th className={thClass}>MFA</th><th className={thClass}>Last login</th><th className={thClass}>Status</th><th className={`${thClass} text-right`}>Actions</th></tr></thead><tbody>{rows.map((user) => <tr key={user.id} className="hover:bg-slate-50"><td className={tdClass}><button type="button" onClick={() => setSelectedId(user.id)} className="text-left"><span className="block font-bold text-slate-950">{user.name}</span><span className="text-xs text-slate-500">{user.employeeId} - {user.email}</span></button></td><td className={tdClass}>{user.office}</td><td className={tdClass}>{user.roles.join(', ')}</td><td className={tdClass}>{user.accountType}</td><td className={tdClass}><StatusChip status={user.mfa} /></td><td className={tdClass}>{user.lastLogin}</td><td className={tdClass}><StatusChip status={user.status} /></td><td className={`${tdClass} text-right`}><ActionMenu actions={[{ label: 'View account', onClick: () => setSelectedId(user.id) }, { label: 'Reset password', onClick: () => setToast(`Password reset issued for ${user.name}.`) }, { label: 'Terminate sessions', onClick: () => setToast(`Active sessions terminated for ${user.name}.`) }, { label: user.status === 'Locked' ? 'Unlock account' : 'Deactivate account', danger: user.status !== 'Locked', onClick: () => updateUser(user.id, { status: user.status === 'Locked' ? 'Active' : 'Scheduled deactivation' }, `${user.name} account status updated.`) }]} /></td></tr>)}</tbody></table></TableWrap>
    </Panel>
    <DetailDrawer open={Boolean(selected)} title={selected?.name ?? 'Account details'} onClose={() => setSelectedId(null)}>{selected && <div className="space-y-5"><div className="grid grid-cols-2 gap-3">{[['Employee ID', selected.employeeId], ['Account ID', selected.id], ['Email', selected.email], ['Office', selected.office], ['Account type', selected.accountType], ['Last login', selected.lastLogin]].map(([label, value]) => <div key={label} className="border border-slate-200 p-3"><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-1 break-words text-sm font-semibold text-slate-900">{value}</p></div>)}</div><Panel title="Access and security"><div className="space-y-3 p-4"><div className="flex items-center justify-between"><span className="text-sm text-slate-600">Assigned roles</span><span className="text-sm font-bold">{selected.roles.join(', ')}</span></div><div className="flex items-center justify-between"><span className="text-sm text-slate-600">MFA</span><StatusChip status={selected.mfa} /></div><div className="flex items-center justify-between"><span className="text-sm text-slate-600">Account status</span><StatusChip status={selected.status} /></div></div></Panel><div className="flex flex-wrap gap-2"><SecondaryButton onClick={() => setToast('Edit mode opened in mock state.')}>Edit profile</SecondaryButton><SecondaryButton onClick={() => setToast('Password reset prepared.')}>Reset password</SecondaryButton><SecondaryButton onClick={() => setToast('Sessions terminated.')}>Terminate sessions</SecondaryButton></div><p className="text-xs text-slate-500">Production actions require backend authorization and create append-only audit events.</p></div>}</DetailDrawer>
    <DetailDrawer open={creating} title="Create account" onClose={() => setCreating(false)}><AccountForm onSave={(user) => { setUsers((current) => [user, ...current]); setCreating(false); setToast(`${user.name} was added to the account directory.`); }} /></DetailDrawer>
    <Toast message={toast} />
  </div>;
}

function AccountForm({ onSave }: Readonly<{ onSave: (user: AdminUser) => void }>) {
  return <form className="space-y-4" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const sequence = String(adminUsers.length + Math.floor(Date.now() / 1000) % 900).padStart(3, '0'); onSave({ id: `USR-${sequence}`, employeeId: String(data.get('employeeId')), name: String(data.get('name')), email: String(data.get('email')), office: String(data.get('office')), roles: [String(data.get('role'))], accountType: String(data.get('accountType')) as AdminUser['accountType'], mfa: 'Not enrolled', lastLogin: 'Never', status: 'Active' }); }}><div className="grid gap-4 sm:grid-cols-2"><Field label="Employee ID"><input name="employeeId" required pattern="CICC-[0-9]{4}" title="Use format CICC-0000" className={inputClass} placeholder="CICC-0000" /></Field><Field label="Account type"><select name="accountType" className={inputClass}><option>Employee</option><option>Privileged</option><option>Service</option></select></Field></div><Field label="Full name"><input name="name" required minLength={3} className={inputClass} /></Field><Field label="Government email"><input name="email" required type="email" pattern=".+@cicc\.gov\.ph" title="Use a cicc.gov.ph email address" className={inputClass} placeholder="name@cicc.gov.ph" /></Field><Field label="Organizational unit"><select name="office" className={inputClass}>{organizationUnits.slice(1).map((unit) => <option key={unit.id}>{unit.name}</option>)}</select></Field><Field label="Initial role"><select name="role" className={inputClass}>{adminRoles.map((role) => <option key={role.id}>{role.name}</option>)}</select></Field><div className="border border-blue-200 bg-blue-50 p-3 text-xs text-blue-800">Only identity information required for AIMRS access is collected. HR, payroll, leave, and performance data are outside system scope.</div><PrimaryButton type="submit">Create account</PrimaryButton></form>;
}

function RolesPage() {
  const [roles, setRoles] = useState<AdminRole[]>(adminRoles);
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState('All');
  const [selected, setSelected] = useState<(typeof adminRoles)[number] | null>(null);
  const [creating, setCreating] = useState(false);
  const [toast, setToast] = useState('');
  const rows = roles.filter((role) => (filter === 'All' || role.privilege === filter || role.reviewStatus === filter) && Object.values(role).join(' ').toLowerCase().includes(search.toLowerCase()));
  return <div className="space-y-4"><AdminPageHeader title="Roles & Permissions" detail="Define role purpose, organizational scope, and effective permissions using least-privilege and separation-of-duty controls." action={<PrimaryButton icon={Plus} onClick={() => setCreating(true)}>Create role</PrimaryButton>} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Defined roles" value="7" detail="One administrative role" tone="blue" icon={KeyRound} /><MetricCard label="Privileged users" value="24" detail="Across five elevated roles" tone="amber" icon={Users} /><MetricCard label="Reviews due" value="2" detail="One role overdue" tone="red" icon={UserCheck} /><MetricCard label="Conflicts detected" value="1" detail="Approval and fulfillment overlap" tone="red" icon={ShieldCheck} /></div>
    <SearchToolbar value={search} onChange={setSearch} filterLabel="All roles" filterValue={filter} filterOptions={['All', 'Standard', 'Elevated', 'Administrative', 'Read only', 'Review due', 'Overdue']} onFilterChange={setFilter} />
    <Panel title="Role Catalogue" detail="Role ownership, scope, population, and review status"><TableWrap><table className="w-full"><thead><tr><th className={thClass}>Role</th><th className={thClass}>Scope</th><th className={thClass}>Users</th><th className={thClass}>Permissions</th><th className={thClass}>Privilege</th><th className={thClass}>Owner</th><th className={thClass}>Last reviewed</th><th className={`${thClass} text-right`}>Actions</th></tr></thead><tbody>{rows.map((role) => <tr key={role.id} className="hover:bg-slate-50"><td className={tdClass}><button onClick={() => setSelected(role)} className="text-left font-bold text-slate-950" type="button">{role.name}<span className="block text-xs font-normal text-slate-500">{role.id}</span></button></td><td className={tdClass}>{role.scope}</td><td className={tdClass}>{role.users}</td><td className={tdClass}>{role.permissions}</td><td className={tdClass}><StatusChip status={role.privilege} /></td><td className={tdClass}>{role.owner}</td><td className={tdClass}>{role.lastReviewed}<span className="mt-1 block"><StatusChip status={role.reviewStatus} /></span></td><td className={`${tdClass} text-right`}><ActionMenu actions={[{ label: 'View permissions', onClick: () => setSelected(role) }, { label: 'Assign user', onClick: () => setToast(`Assignment workflow opened for ${role.name}.`) }, { label: 'Start access review', onClick: () => setToast(`Access review prepared for ${role.name}.`) }]} /></td></tr>)}</tbody></table></TableWrap></Panel>
    <Panel title="Permission Matrix" detail="Effective capability by operational role; backend guards remain the security enforcement point"><TableWrap><table className="w-full"><thead><tr><th className={thClass}>Capability group</th><th className={thClass}>Employee</th><th className={thClass}>Approving officer</th><th className={thClass}>IT custodian</th><th className={thClass}>Property custodian</th><th className={thClass}>Master admin</th></tr></thead><tbody>{permissionGroups.map((item) => <tr key={item.group}><td className={`${tdClass} font-bold text-slate-900`}>{item.group}</td><td className={tdClass}>{item.employee}</td><td className={tdClass}>{item.approver}</td><td className={tdClass}>{item.ict}</td><td className={tdClass}>{item.property}</td><td className={tdClass}>{item.admin}</td></tr>)}</tbody></table></TableWrap></Panel>
    <DetailDrawer open={Boolean(selected)} title={selected?.name ?? 'Role'} onClose={() => setSelected(null)}>{selected && <div className="space-y-4"><div className="border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900"><strong>Effective access preview:</strong> {selected.scope}. Changes require backend RBAC implementation before production use.</div>{[['Role owner', selected.owner], ['Assigned users', String(selected.users)], ['Permission count', String(selected.permissions)], ['Privilege level', selected.privilege], ['Last reviewed', selected.lastReviewed]].map(([label, value]) => <div key={label} className="flex justify-between gap-4 border-b border-slate-100 pb-3 text-sm"><span className="text-slate-500">{label}</span><span className="text-right font-semibold text-slate-900">{value}</span></div>)}<PrimaryButton onClick={() => setToast(`${selected.name} was opened as a new editable draft.`)}>Create editable draft</PrimaryButton></div>}</DetailDrawer>
    <DetailDrawer open={creating} title="Create role" onClose={() => setCreating(false)}><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const role: AdminRole = { id: `ROL-${String(roles.length + 1).padStart(3, '0')}`, name: String(data.get('name')), scope: String(data.get('scope')), users: 0, permissions: Number(data.get('permissions')), privilege: String(data.get('privilege')) as AdminRole['privilege'], owner: String(data.get('owner')), lastReviewed: 'Not reviewed', reviewStatus: 'Review due' }; setRoles((current) => [...current, role]); setCreating(false); setToast(`${role.name} role draft was created.`); }}><Field label="Role name"><input name="name" required minLength={3} className={inputClass} /></Field><Field label="Organizational scope"><input name="scope" required className={inputClass} placeholder="Own records, assigned unit, or agency-wide" /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Privilege level"><select name="privilege" className={inputClass}><option>Standard</option><option>Elevated</option><option>Administrative</option><option>Read only</option></select></Field><Field label="Permission count"><input name="permissions" type="number" min="1" max="50" defaultValue="1" className={inputClass} /></Field></div><Field label="Role owner"><input name="owner" required className={inputClass} placeholder="Accountable office or unit" /></Field><div className="border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900">The role remains a draft until its permissions are reviewed for least privilege and separation-of-duty conflicts.</div><PrimaryButton type="submit">Create role draft</PrimaryButton></form></DetailDrawer><Toast message={toast} /></div>;
}

function AccessReviewsPage() {
  const [reviews, setReviews] = useState(accessReviews);
  const [creating, setCreating] = useState(false);
  const [toast, setToast] = useState('');
  return <div className="space-y-4"><AdminPageHeader title="Access Reviews" detail="Certify privileged, dormant, and custodian access on a recurring schedule while preserving reviewer evidence." action={<PrimaryButton icon={Plus} onClick={() => setCreating(true)}>Start review</PrimaryButton>} />
    <div className="grid gap-3 sm:grid-cols-3"><MetricCard label="Open reviews" value="2" detail="32 accounts in scope" tone="amber" icon={UserCheck} /><MetricCard label="At risk" value="1" detail="Due within two days" tone="red" icon={ShieldCheck} /><MetricCard label="Certified this quarter" value="8" detail="No unresolved exceptions" tone="green" icon={Users} /></div>
    <Panel title="Certification Campaigns" detail="Reviewers retain, revoke, or modify access with a recorded justification"><div className="divide-y divide-slate-100">{reviews.map((review) => <article key={review.id} className="grid gap-4 p-4 lg:grid-cols-[1.4fr_1fr_1fr_auto] lg:items-center"><div><p className="font-bold text-slate-950">{review.name}</p><p className="mt-1 text-xs text-slate-500">{review.id} - {review.scope}</p></div><div><p className="text-xs text-slate-500">Owner</p><p className="text-sm font-semibold">{review.owner}</p></div><div><div className="flex justify-between text-xs"><span>{review.progress}% complete</span><span>Due {review.due}</span></div><div className="mt-2 h-2 bg-slate-100"><div className={`h-full ${review.status === 'At risk' ? 'bg-red-500' : 'bg-blue-600'}`} style={{ width: `${review.progress}%` }} /></div></div><div className="flex items-center justify-between gap-3 lg:justify-end"><StatusChip status={review.status} /><SecondaryButton onClick={() => { setReviews((current) => current.map((item) => item.id === review.id ? { ...item, progress: Math.min(100, item.progress + 10), status: item.progress >= 90 ? 'Completed' : 'In progress' } : item)); setToast(`${review.name} certification progress was updated.`); }}>Review</SecondaryButton></div></article>)}</div></Panel>
    <DetailDrawer open={creating} title="Start access review" onClose={() => setCreating(false)}><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const review = { id: `REV-2026-${String(reviews.length + 1).padStart(2, '0')}`, name: String(data.get('name')), owner: String(data.get('owner')), scope: String(data.get('scope')), due: String(data.get('due')), progress: 0, status: 'In progress' }; setReviews((current) => [review, ...current]); setCreating(false); setToast(`${review.name} was started.`); }}><Field label="Campaign name"><input name="name" required className={inputClass} /></Field><Field label="Accounts or roles in scope"><input name="scope" required className={inputClass} placeholder="Example: All privileged accounts" /></Field><Field label="Review owner"><input name="owner" required className={inputClass} /></Field><Field label="Due date"><input name="due" required type="date" className={inputClass} /></Field><PrimaryButton type="submit">Start certification</PrimaryButton></form></DetailDrawer><Toast message={toast} /></div>;
}

function OrganizationPage() {
  const [units, setUnits] = useState(organizationUnits);
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState('All');
  const [selected, setSelected] = useState<(typeof organizationUnits)[number] | null>(null);
  const [creating, setCreating] = useState(false);
  const [toast, setToast] = useState('');
  const rows = units.filter((unit) => (filter === 'All' || unit.type === filter || unit.status === filter) && Object.values(unit).join(' ').toLowerCase().includes(search.toLowerCase()));
  return <div className="space-y-4"><AdminPageHeader title="Organization Structure" detail="Maintain CICC offices, divisions, sections, and reporting relationships used for access scope, approvals, and custody." action={<PrimaryButton icon={Plus} onClick={() => setCreating(true)}>Add unit</PrimaryButton>} />
    <div className="grid min-w-0 gap-4 xl:grid-cols-[320px_minmax(0,1fr)]"><Panel title="Hierarchy" detail="Reporting structure"><div className="p-3"><div className="border-l-2 border-blue-200 pl-3"><p className="py-2 text-sm font-bold text-slate-950">CICC</p>{units.filter((unit) => unit.parent === 'CICC').map((unit) => <div key={unit.id} className="border-l border-slate-200 pl-3"><button type="button" onClick={() => setSelected(unit)} className="w-full py-2 text-left text-sm font-semibold text-slate-700 hover:text-blue-700">{unit.name}</button>{units.filter((child) => child.parent === unit.name).map((child) => <button key={child.id} type="button" onClick={() => setSelected(child)} className="block w-full border-l border-slate-200 py-2 pl-3 text-left text-xs text-slate-600 hover:text-blue-700">{child.name}</button>)}</div>)}</div></div></Panel><div className="min-w-0 space-y-4"><SearchToolbar value={search} onChange={setSearch} filterLabel="All unit types" filterValue={filter} filterOptions={['All', 'Agency', 'Division', 'Service', 'Section', 'Unit', 'Active']} onFilterChange={setFilter} /><Panel title="Organizational Units" detail={`${rows.length} hierarchy records`}><TableWrap><table className="min-w-[1050px] w-full"><thead><tr><th className={thClass}>Unit</th><th className={thClass}>Type</th><th className={thClass}>Parent</th><th className={thClass}>Unit head</th><th className={thClass}>Users</th><th className={thClass}>Custodian</th><th className={thClass}>Status</th><th className={`${thClass} text-right`}>Actions</th></tr></thead><tbody>{rows.map((unit) => <tr key={unit.id} className="hover:bg-slate-50"><td className={tdClass}><button type="button" onClick={() => setSelected(unit)} className="text-left font-bold text-slate-950">{unit.name}<span className="block text-xs font-normal text-slate-500">{unit.code}</span></button></td><td className={tdClass}>{unit.type}</td><td className={tdClass}>{unit.parent}</td><td className={tdClass}>{unit.head}</td><td className={tdClass}>{unit.users}</td><td className={tdClass}>{unit.custodian}</td><td className={tdClass}><StatusChip status={unit.status} /></td><td className={`${tdClass} text-right`}><ActionMenu actions={[{ label: 'View unit', onClick: () => setSelected(unit) }, { label: 'Mark inactive', onClick: () => { setUnits((current) => current.map((item) => item.id === unit.id ? { ...item, status: 'Inactive' } : item)); setToast(`${unit.name} marked inactive in mock state.`); } }, { label: 'Review dependencies', onClick: () => setToast(`${unit.users} user dependencies and related workflow links found.`) }]} /></td></tr>)}</tbody></table></TableWrap></Panel></div></div>
    <DetailDrawer open={Boolean(selected)} title={selected?.name ?? 'Organizational unit'} onClose={() => setSelected(null)}>{selected && <div className="space-y-4">{[['Unit code', selected.code], ['Type', selected.type], ['Parent', selected.parent], ['Unit head', selected.head], ['Assigned users', String(selected.users)], ['Custodian coverage', selected.custodian]].map(([label, value]) => <div key={label} className="flex justify-between gap-4 border-b border-slate-100 pb-3 text-sm"><span className="text-slate-500">{label}</span><span className="text-right font-semibold">{value}</span></div>)}<div className="border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900">Before deactivation, AIMRS checks users, assets, approval workflows, and custodian assignments that depend on this unit.</div><SecondaryButton onClick={() => setToast(`${selected.users} user dependencies checked; no destructive action was performed.`)}>Review dependencies</SecondaryButton></div>}</DetailDrawer>
    <DetailDrawer open={creating} title="Add organizational unit" onClose={() => setCreating(false)}><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const unit = { id: `OU-${String(units.length + 1).padStart(3, '0')}`, code: String(data.get('code')), name: String(data.get('name')), type: String(data.get('type')), parent: String(data.get('parent')), head: String(data.get('head')), users: 0, custodian: 'Unassigned', status: 'Active' }; setUnits((current) => [...current, unit]); setCreating(false); setToast(`${unit.name} was added to the organization hierarchy.`); }}><div className="grid gap-4 sm:grid-cols-2"><Field label="Unit code"><input name="code" required className={inputClass} placeholder="AS-UNIT" /></Field><Field label="Unit type"><select name="type" className={inputClass}><option>Division</option><option>Service</option><option>Section</option><option>Unit</option></select></Field></div><Field label="Unit name"><input name="name" required className={inputClass} /></Field><Field label="Parent unit"><select name="parent" className={inputClass}>{units.map((unit) => <option key={unit.id} value={unit.name}>{unit.name}</option>)}</select></Field><Field label="Unit head"><input name="head" required className={inputClass} /></Field><PrimaryButton type="submit">Add unit</PrimaryButton></form></DetailDrawer><Toast message={toast} /></div>;
}
